// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./components/article/articleItem.vue')['default']
    ButtonRepo: typeof import('./components/ButtonRepo.vue')['default']
    ColorModeSwitch: typeof import('./components/ColorModeSwitch.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    README: typeof import('./components/README.md')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    Waves: typeof import('./components/Waves/index.vue')['default']
  }
}

export { }
